[package]
name = "mini-pic"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.18.0", features = ["wgpu", "dataset", "network", "train", "tui", "metrics"] }
serde = "1.0.228"
serde_json = "1.0.145"
rayon = "1.10.0"
derive-new = "0.7.0"
csv = "1.3.1"
rand = "0.8.5"
itertools = "0.14.0"
image = "0.25.0"
tokenizers = "0.20.3"

[lib]
name = "mini_pic"
path = "src/lib.rs"

[[bin]]
name = "preprocess"
path = "src/bin/preprocess.rs"

[[bin]]
name = "train_tokenizer"
path = "src/bin/train_tokenizer.rs"

[[bin]]
name = "augment"
path = "src/bin/augment.rs"